/**
 * Trip-type tags per country (ISO 3166-1 alpha-2).
 * A country can have multiple tags — the quiz matches on the user's chosen type.
 *
 * Tags:
 *   beach     — beaches, islands, coastal relaxation
 *   culture   — vibrant cities, food scenes, contemporary culture
 *   nature    — wildlife, national parks, landscapes
 *   adventure — hiking, trekking, extreme sports, remote terrain
 *   history   — ancient ruins, UNESCO heritage, archaeological sites
 */
export type TripType = 'beach' | 'culture' | 'nature' | 'adventure' | 'history';

export const COUNTRY_TAGS: Record<string, TripType[]> = {
  // ── Europe ────────────────────────────────────────────────────────────────
  FR: ['culture', 'history', 'beach'],
  ES: ['culture', 'history', 'beach'],
  IT: ['culture', 'history', 'beach'],
  PT: ['culture', 'history', 'beach'],
  GR: ['history', 'beach', 'culture'],
  HR: ['beach', 'history', 'culture'],
  TR: ['history', 'beach', 'culture'],
  MT: ['history', 'beach'],
  CY: ['beach', 'history'],
  GB: ['culture', 'history'],
  DE: ['culture', 'history'],
  NL: ['culture'],
  BE: ['culture', 'history'],
  AT: ['culture', 'adventure'],
  CH: ['adventure', 'nature', 'culture'],
  CZ: ['culture', 'history'],
  HU: ['culture', 'history'],
  PL: ['culture', 'history'],
  RO: ['nature', 'history', 'adventure'],
  BG: ['history', 'beach'],
  RS: ['culture', 'history'],
  ME: ['beach', 'nature', 'adventure'],
  AL: ['beach', 'nature', 'history'],
  MK: ['history', 'nature'],
  BA: ['culture', 'history', 'nature'],
  SI: ['nature', 'adventure', 'culture'],
  SK: ['history', 'nature', 'adventure'],
  NO: ['nature', 'adventure'],
  SE: ['nature', 'culture'],
  FI: ['nature', 'adventure'],
  DK: ['culture'],
  IS: ['nature', 'adventure'],
  IE: ['nature', 'culture'],
  LT: ['culture', 'history'],
  LV: ['culture', 'history'],
  EE: ['culture', 'history'],
  BY: ['culture', 'history'],
  UA: ['culture', 'history'],
  MD: ['culture', 'nature'],
  LU: ['culture', 'history'],
  LI: ['nature', 'adventure'],
  SM: ['culture', 'history'],
  VA: ['history', 'culture'],
  MC: ['culture'],
  AD: ['adventure', 'nature'],
  XK: ['culture', 'nature'],

  // ── Middle East ───────────────────────────────────────────────────────────
  AE: ['culture', 'beach'],
  QA: ['culture', 'history'],
  SA: ['history', 'culture'],
  JO: ['history', 'adventure'],
  IL: ['history', 'culture'],
  LB: ['history', 'culture'],
  OM: ['history', 'nature', 'adventure'],
  BH: ['culture', 'history'],
  KW: ['culture'],
  IQ: ['history'],
  IR: ['history', 'culture'],
  SY: ['history'],
  YE: ['history', 'nature'],
  PS: ['history'],

  // ── Asia ──────────────────────────────────────────────────────────────────
  JP: ['culture', 'history', 'nature'],
  CN: ['history', 'culture', 'nature'],
  KR: ['culture', 'history'],
  TW: ['culture', 'nature'],
  HK: ['culture'],
  MO: ['culture', 'history'],
  TH: ['beach', 'culture', 'history'],
  VN: ['history', 'culture', 'beach', 'nature'],
  KH: ['history', 'culture'],
  LA: ['nature', 'culture', 'history'],
  MM: ['history', 'culture', 'nature'],
  MY: ['beach', 'culture', 'nature'],
  SG: ['culture'],
  ID: ['beach', 'nature', 'culture', 'adventure'],
  PH: ['beach', 'nature', 'adventure'],
  BN: ['nature', 'culture'],
  IN: ['history', 'culture', 'nature'],
  LK: ['history', 'beach', 'nature'],
  NP: ['adventure', 'nature'],
  BT: ['nature', 'culture', 'adventure'],
  BD: ['culture', 'history'],
  PK: ['history', 'adventure', 'nature'],
  AF: ['history', 'adventure'],
  MN: ['adventure', 'nature'],
  KZ: ['nature', 'history', 'adventure'],
  UZ: ['history', 'culture'],
  TM: ['history', 'adventure'],
  KG: ['adventure', 'nature'],
  TJ: ['adventure', 'nature'],
  AZ: ['culture', 'history', 'adventure'],
  GE: ['culture', 'history', 'adventure', 'nature'],
  AM: ['history', 'culture', 'adventure'],

  // ── South Asia / Oceania ──────────────────────────────────────────────────
  AU: ['beach', 'nature', 'adventure'],
  NZ: ['nature', 'adventure', 'beach'],
  FJ: ['beach', 'nature'],
  PG: ['nature', 'adventure'],
  SB: ['beach', 'nature'],
  VU: ['beach', 'nature', 'adventure'],
  WS: ['beach', 'nature'],
  TO: ['beach', 'nature'],
  FM: ['beach', 'nature'],
  PW: ['beach', 'nature'],
  MH: ['beach'],
  KI: ['beach'],
  NR: ['beach'],

  // ── Africa ────────────────────────────────────────────────────────────────
  EG: ['history', 'culture'],
  MA: ['history', 'culture', 'adventure'],
  TN: ['history', 'beach', 'culture'],
  DZ: ['history', 'nature', 'adventure'],
  LY: ['history'],
  ET: ['history', 'nature', 'culture'],
  KE: ['nature', 'adventure'],
  TZ: ['nature', 'adventure', 'beach'],
  UG: ['nature', 'adventure'],
  RW: ['nature', 'adventure'],
  ZA: ['nature', 'adventure', 'beach', 'culture'],
  NA: ['nature', 'adventure'],
  BW: ['nature'],
  ZW: ['nature', 'history'],
  ZM: ['nature', 'adventure'],
  MZ: ['beach', 'nature'],
  MG: ['nature', 'adventure', 'beach'],
  MU: ['beach'],
  SC: ['beach', 'nature'],
  ER: ['history', 'nature'],
  DJ: ['nature', 'adventure'],
  SO: ['history'],
  NG: ['culture', 'history'],
  GH: ['culture', 'history', 'beach'],
  SN: ['culture', 'beach', 'nature'],
  CI: ['culture', 'beach'],
  GM: ['beach', 'nature'],
  ML: ['history', 'culture'],
  BF: ['culture', 'history'],
  NE: ['history', 'adventure'],
  TD: ['history', 'nature', 'adventure'],
  CM: ['nature', 'culture'],
  CF: ['nature'],
  GA: ['nature'],
  CG: ['nature'],
  CD: ['nature', 'adventure'],
  AO: ['nature', 'culture'],
  BI: ['nature'],
  MR: ['history', 'adventure'],
  GN: ['nature', 'culture'],
  GW: ['beach', 'nature'],
  SL: ['beach', 'nature'],
  LR: ['beach', 'nature'],
  TG: ['beach', 'culture'],
  BJ: ['culture', 'history'],
  GQ: ['nature'],
  CV: ['beach', 'culture'],
  SS: ['nature'],
  SD: ['history', 'culture'],
  KM: ['beach', 'nature'],
  MW: ['nature', 'beach'],
  SZ: ['nature', 'culture'],
  LS: ['adventure', 'nature'],

  // ── Americas ──────────────────────────────────────────────────────────────
  US: ['culture', 'nature', 'adventure', 'history'],
  CA: ['nature', 'adventure', 'culture'],
  MX: ['history', 'culture', 'beach'],
  GT: ['history', 'culture', 'nature'],
  BZ: ['nature', 'beach', 'history'],
  HN: ['history', 'beach', 'nature'],
  SV: ['history', 'beach', 'adventure'],
  NI: ['history', 'nature', 'beach'],
  CR: ['nature', 'adventure', 'beach'],
  PA: ['nature', 'culture', 'beach'],
  CU: ['culture', 'history', 'beach'],
  JM: ['beach', 'culture'],
  HT: ['history', 'culture'],
  DO: ['beach', 'culture'],
  BS: ['beach'],
  TT: ['culture', 'beach'],
  AG: ['beach'],
  BB: ['beach', 'culture'],
  LC: ['beach', 'nature'],
  VC: ['beach', 'nature'],
  GD: ['beach', 'nature'],
  DM: ['nature', 'adventure'],
  KN: ['beach'],
  CO: ['culture', 'nature', 'history', 'beach'],
  VE: ['nature', 'beach', 'adventure'],
  GY: ['nature', 'adventure'],
  SR: ['nature', 'culture'],
  BR: ['beach', 'nature', 'culture', 'adventure'],
  EC: ['nature', 'adventure', 'history'],
  PE: ['history', 'adventure', 'nature'],
  BO: ['history', 'adventure', 'nature'],
  CL: ['nature', 'adventure', 'beach'],
  AR: ['nature', 'adventure', 'culture', 'beach'],
  UY: ['beach', 'culture'],
  PY: ['nature', 'culture'],

  // ── Central Asia / Caucasus (additional) ─────────────────────────────────
  RU: ['culture', 'history', 'nature', 'adventure'],
  TL: ['beach', 'nature'],
};

export interface QuizCountry {
  identifier: string;
  alpha2: string;
  name: string;
  tags: TripType[];
  bestMonths: number[];
}
